#use_frameworks!

# pod 'VideoCore', :git => 'https://github.com/goodow/VideoCore.git'
pod 'glm', :git => 'https://github.com/maxcampolo/glm.git'

target 'GDLiveStreaming_Example' do
  pod 'VideoCore', path: '../VideoCore'
  pod 'GDLiveStreaming', :path => '../'
end

target 'GDLiveStreaming_Tests' do
  pod 'GDLiveStreaming', :path => '../'
end
