#use_frameworks!

# pod 'VideoCore', :git => 'https://github.com/goodow/VideoCore.git'
pod 'glm', :podspec => 'https://raw.githubusercontent.com/goodow/GDLiveStreaming/master/glm.podspec'
pod 'VideoCore', path: '../VideoCore'

target 'GDLiveStreaming_Example' do
  pod 'GDLiveStreaming', :path => '../'
end

target 'GDLiveStreaming_Tests' do
  pod 'GDLiveStreaming', :path => '../'
end
